language: node_js
node_js:
    #- "8"
    - "node"

dist: trusty

addons:
  chrome: stable

before_script:
    - npm run devServer & # start Web server
    - sleep 3 # give Web server some time to bind to sockets, etc

cache:
    directories:
        - ~/.npm
