language: node_js
node_js:
    - "8"
    - "node"

dist: trusty

addons:
  chrome: stable

before_script:
    - export DISPLAY=:99.0
    - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
    - sh -e /etc/init.d/xvfb start
    - curl -L https://raw.githubusercontent.com/GoogleChrome/lighthouse/v2.1.0/lighthouse-core/scripts/download-chrome.sh | bash
    - npx http-server -p 8080 &  # start a Web server
    - sleep 3 # give Web server some time to bind to sockets, etc

cache:
    directories:
        - ~/.npm
